# Generated by Django 4.2 on 2023-05-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codebotApp", "0002_code_api_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="code",
            name="api_key",
        ),
    ]
